### PR TITLE
Common Terms and Conventions - #2665

### PR DESCRIPTION
**Pull request by mwmentor**
I have updated the list to direct attention to content sections and the Further Reading section of the document.  I have included updates to the Further Reading section of the document with this PR as they are integral to the completion of the CT&C page.

### CODE REVIEW

**Comment by mwmentor** [comment]
@pedrosousabarreto Hi Pedro, please could you review and advise should you find any issues.  Thanks. -M 😄

**Review by pedrosousabarreto — CHANGES_REQUESTED** [review]
There is a http://localhost:8080 that was left from dev, and as much as possible use absolute path

**Comment by mwmentor** [comment]
@pedrosousabarreto Hi Pedro: When you have a moment, please could you review the changes that I made, and let me know if there are any further issues. If not please okay it so that I can merge and delete this branch. Thanks. -M 👍

**Review by pedrosousabarreto — APPROVED** [review]
Looks good

**Comment by mwmentor** [comment]
Thanks @pedrosousabarreto - merge and branch deleted. 😄

**Pull request merged**
