### PR TITLE
ML2RA2-Security-#2686

### PR DESCRIPTION
**Pull request by mwmentor**
I have updated all of the images to include the latest workflow versions, and created consistent scale and font height.  Waiting for @godfreykutumela to comment on copy and update where appropriate to do so.

### CODE REVIEW

**Comment by mwmentor** [comment]
@pedrosousabarreto @mdebarros @godfreykutumela Hi there folks:  When you have a moment, please review this PR and let me know if you have any queries, or authorize merging.  Thanks.

**Comment by mwmentor** [comment]
@godfreykutumela Hi Godfrey: There are still some copy queries affiliated with this PR.  Please could you view [Ticket #2686](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2686).  Thanks. 😄

**Review by pedrosousabarreto — DISMISSED** [review]
Looks good

**Comment by mwmentor** [comment]
@pedrosousabarreto Hi Pedro:  Please could you review and approve again.  I made some improvements to the images which replaced the previously approved set.  Thanks so much.

**Comment by mwmentor** [comment]
Hi Godfrey:  Thanks so much, that's great.  I have handled the images which just needed a bit of tweaking to scale, font height, and also text case.  I am going to rearrange the copy in the opening section of the page, but apart from that, unless Pedro wants any further changes, I guess that there is nothing left to do. Thanks so much 👍  😄

**Review by godfreykutumela — APPROVED** [review]

**Pull request merged**
